version: 1
config:
- SeqNum: 1
  Section no: '11.1'
  Section title: 人口学和基线特征
  table no: 14.1.1
  title: 受试者基线特征（FAS）
  pop: FAS
  MacVar: PStab
  Datasets: t_demo
  Trtlab: A组^[a]|B组|合计
  Subgrp: ''
  Adcols: ''
  Varlab: ''
  Labparm: ''
  footnote1: FAS=全分析集；SD=标准差；^[a]表示A组
  footnote2: ''
  footnote3: ''
  footnote4: ''
  footnote5: ''
  footnote6: ''
  footnote7: ''
  PgmNotes: 来源：ADSL数据集
  ByseqL: null
  RefTFL: ''
  Dutoffdate: ''
  Source_Data: ADSL
- SeqNum: 2
  Section no: '16.2'
  Section title: 受试者清单
  table no: 16.2.1
  title: 受试者基本信息清单（FAS）
  pop: FAS
  MacVar: RptList
  Datasets: l_subj
  Trtlab: ''
  Subgrp: ''
  Adcols: ''
  Varlab: ''
  Labparm: ''
  footnote1: FAS=全分析集
  footnote2: ''
  footnote3: ''
  footnote4: ''
  footnote5: ''
  footnote6: ''
  footnote7: ''
  PgmNotes: 来源：ADSL数据集
  ByseqL: USUBJID
  RefTFL: ''
  Dutoffdate: ''
  Source_Data: ADSL
- SeqNum: 3
  Section no: '11.1'
  Section title: 人口学和基线特征
  table no: 14.1.1.1
  title: ''
  pop: ''
  MacVar: mtext
  Datasets: ''
  Trtlab: ''
  Subgrp: ''
  Adcols: ''
  Varlab: ''
  Labparm: ''
  footnote1: ''
  footnote2: ''
  footnote3: ''
  footnote4: ''
  footnote5: ''
  footnote6: ''
  footnote7: ''
  PgmNotes: ''
  ByseqL: null
  RefTFL: 14.1.1
  Dutoffdate: ''
  Source_Data: ''
- SeqNum: 4
  Section no: '11.3'
  Section title: 生存分析
  table no: 14.3.1
  title: PFS的Kaplan-Meier曲线（FAS）
  pop: FAS
  MacVar: KMplot
  Datasets: f_km_pfs
  Trtlab: A组|B组
  Subgrp: ''
  Adcols: ''
  Varlab: ''
  Labparm: ''
  footnote1: PFS=无进展生存期；CI=置信区间
  footnote2: ''
  footnote3: ''
  footnote4: ''
  footnote5: ''
  footnote6: ''
  footnote7: ''
  PgmNotes: 来源：ADTTE数据集，PARAMCD=PFS
  ByseqL: null
  RefTFL: ''
  Dutoffdate: ''
  Source_Data: ADTTE
datasets:
  t_demo:
  - Class: ''
    Label: 年龄（岁）
    Order: 0
    Aval: ''
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: 均数（标准差）
    Order: 1
    Aval: Mean (SD)
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: 中位数（最小值，最大值）
    Order: 1
    Aval: Median (Min, Max)
    exclude: 0
    BlankCol: ''
  - Class: 性别
    Label: ''
    Order: 0
    Aval: ''
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: 男，n（%）
    Order: 1
    Aval: N_PCT_M
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: 女，n（%）
    Order: 1
    Aval: N_PCT_F
    exclude: 0
    BlankCol: ''
  l_subj:
  - Class: ''
    Label: 受试者编号
    Order: 0
    Aval: USUBJID
    exclude: 0
    BlankCol: ''
  list:
  - ListName: l_subj
    Byseq: 1
    Byorder: 1
    Lvalable: 受试者编号
  - ListName: l_subj
    Byseq: 2
    Byorder: 2
    Lvalable: 年龄
  f_km_pfs:
  - Class: ''
    Label: PFS（月）
    Order: 0
    Aval: AVAL
    exclude: 0
    BlankCol: ''
