version: 1
config:
- SeqNum: 1
  Section no: '14.1'
  Section title: 参与者特征
  cat: 表
  table no: 14.1.1.1
  title: 参与者分布
  pop: 所有筛选参与者
  MacVar: PStab
  Datasets: ds_1
  Trtlab: IMM01联合阿扎胞苷|安慰剂联合阿扎胞苷|合计
  Subgrp: ''
  Adcols: ''
  Varlab: ''
  Labparm: ''
  footnote1: 注： 除筛选失败和随机入组的分母为筛选总例数外，其余百分数的计算均以随机入组人数作为分母。
  footnote2: ''
  footnote3: ''
  footnote4: ''
  footnote5: ''
  footnote6: ''
  footnote7: ''
  PgmNotes: ''
  ByseqL: ~
  RefTFL: ''
- SeqNum: 2
  Section no: '14.1'
  Section title: 参与者特征
  cat: 表
  table no: 14.1.3.1
  title: 人口学与基线特征
  pop: ITT
  MacVar: PStab
  Datasets: ds_2
  Trtlab: IMM01联合阿扎胞苷|安慰剂联合阿扎胞苷|合计
  Subgrp: ''
  Adcols: ''
  Varlab: ''
  Labparm: ''
  footnote1: 注： 年龄（岁）=（知情同意日期-出生日期）/365.25，向下取整。
  footnote2: 14.2 疗效分析
  footnote3: 14.3 安全性分析
  footnote4: ''
  footnote5: ''
  footnote6: ''
  footnote7: ''
  PgmNotes: 编程说明： 对各参数，若存在缺失数据，则增加“缺失”分类。
  ByseqL: ~
  RefTFL: ''
- SeqNum: 3
  Section no: '14.3'
  Section title: 安全性分析
  cat: 表
  table no: 14.3.1.2.1
  title: 按照MedDRA编码的系统器官分类和首选术语总结治疗期出现的不良事件
  pop: SS
  MacVar: PStab
  Datasets: ds_3
  Trtlab: IMM01联合阿扎胞苷|安慰剂联合阿扎胞苷
  Subgrp: 所有级别|≥3级
  Adcols: ''
  Varlab: ''
  Labparm: 编程说明： 对各参数，若存在缺失数据，则增加“缺失”分类。
  footnote1: 注： MedDRA version 28.1。 CTCAE使用不良事件通用术语标准版5.0。 同一参与者多次发生的不良事件，在计算例数时仅在CTCAE等级最严重程度计数一次。
    治疗期出现的不良事件（TEAE）定义为：发生于第一次使用研究药物之后；或在使用研究药物之前已发生，但使用研究药物期间加重，至最后一次用药日期+35天区间内或新抗肿瘤治疗前（以先发生者为准）的不良事件。
  footnote2: ''
  footnote3: ''
  footnote4: ''
  footnote5: ''
  footnote6: ''
  footnote7: ''
  PgmNotes: 编程说明： 所有AE表格按照IMM01联合阿扎胞苷组不良事件的发生率的降序进行排序。CTCAE等级中任何等级需要包含missing grade的情况；其余表同理。未编码请显示在表格最后。
  ByseqL: ~
  RefTFL: ''
- SeqNum: 4
  Section no: '14.3'
  Section title: 安全性分析
  cat: 表
  table no: 14.3.3.1.1
  title: 实验室检查：血常规检查结果和相对基线变化值总结
  pop: SS
  MacVar: PStab
  Datasets: ds_4
  Trtlab: IMM01联合阿扎胞苷|安慰剂联合阿扎胞苷
  Subgrp: ''
  Adcols: ''
  Varlab: ''
  Labparm: 参数：白细胞计数（109/L）  <请重复其它参数（单位）>
  footnote1: 注： 基线定义为首次给予研究药物前的末次非缺失测量；
  footnote2: 14.5 免疫原性分析
  footnote3: ''
  footnote4: ''
  footnote5: ''
  footnote6: ''
  footnote7: ''
  PgmNotes: ''
  ByseqL: ~
  RefTFL: ''
- SeqNum: 5
  Section no: '14.5'
  Section title: 免疫原性分析
  cat: 表
  table no: 14.5.1.1
  title: 免疫原性结果按计划访视汇总
  pop: IS
  MacVar: PStab
  Datasets: ds_5
  Trtlab: 指标|IMM01联合阿扎胞苷
  Subgrp: ''
  Adcols: ''
  Varlab: ''
  Labparm: 统计量
  footnote1: ''
  footnote2: ''
  footnote3: ''
  footnote4: ''
  footnote5: ''
  footnote6: ''
  footnote7: ''
  PgmNotes: ''
  ByseqL: ~
  RefTFL: ''
- SeqNum: 6
  Section no: 16.2.1
  Section title: 列表 参与者特征
  cat: 列表
  table no: 16.2.1.3
  title: 参与者分布
  pop: ITT
  MacVar: RptList
  Datasets: list
  Trtlab: 参与者编号|随机入组日期|IMM01/安慰剂首次给药日期（研究日）/末次给药日期（研究日）|IMM01/安慰剂确认结束治疗日期（研究日）|IMM01/安慰剂结束治疗主要原因|阿扎胞苷确认结束治疗日期（研究日）|阿扎胞苷治疗结束主要原因|研究结束日期（研究日）|研究结束原因
  Subgrp: ''
  Adcols: ''
  Varlab: ''
  Labparm: ''
  footnote1: 注： 研究日=事件/检查/评估日期 - 随机日期 + 1。
  footnote2: ''
  footnote3: ''
  footnote4: ''
  footnote5: ''
  footnote6: ''
  footnote7: ''
  PgmNotes: 编程说明： 终止治疗原因若为“其他”，请显示具体原因，如“其他：xxx”；研究结束原因同理。
  ByseqL: ~
  RefTFL: ''
- SeqNum: 7
  Section no: 16.2.2
  Section title: 列表 参与者特征
  cat: 列表
  table no: 16.2.2.1
  title: 重大方案偏离
  pop: ITT
  MacVar: RptList
  Datasets: list
  Trtlab: 参与者编号|重大方案违背分类|详细情况描述
  Subgrp: ''
  Adcols: ''
  Varlab: ''
  Labparm: 编程说明： 终止治疗原因若为“其他”，请显示具体原因，如“其他：xxx”；研究结束原因同理。
  footnote1: 14.4 疗效分析
  footnote2: ''
  footnote3: ''
  footnote4: ''
  footnote5: ''
  footnote6: ''
  footnote7: ''
  PgmNotes: ''
  ByseqL: ~
  RefTFL: ''
datasets:
  ds_1:
  - Class: ''
    Label: 筛选例数
    Order: 0
    Aval: '||xx'
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: 未成功入组
    Order: 1
    Aval: '||xx (xx.x)'
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: 不满足所有入选标准或满足任一排除标准
    Order: 1
    Aval: '||xx (xx.x)'
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: 参与者或其法定代理人撤回知情同意
    Order: 1
    Aval: '||xx (xx.x)'
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: ''
    Order: 0
    Aval: '||'
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: 成功随机入组
    Order: 0
    Aval: xx|xx|xx
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: 随机入组但未给药
    Order: 1
    Aval: xx (xx.x)|xx (xx.x)|xx (xx.x)
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: ''
    Order: 0
    Aval: '||'
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: 终止治疗
    Order: 0
    Aval: xx (xx.x)|xx (xx.x)|xx (xx.x)
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: 参与者死亡
    Order: 1
    Aval: xx (xx.x)|xx (xx.x)|xx (xx.x)
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: 申办方终止研究
    Order: 1
    Aval: xx (xx.x)|xx (xx.x)|xx (xx.x)
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: 妊娠
    Order: 1
    Aval: xx (xx.x)|xx (xx.x)|xx (xx.x)
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: 失访
    Order: 1
    Aval: xx (xx.x)|xx (xx.x)|xx (xx.x)
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: 其他
    Order: 1
    Aval: xx (xx.x)|xx (xx.x)|xx (xx.x)
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: ''
    Order: 0
    Aval: '||'
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: 仍在研究中
    Order: 0
    Aval: xx (xx.x)|xx (xx.x)|xx (xx.x)
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: 退出研究
    Order: 0
    Aval: xx (xx.x)|xx (xx.x)|xx (xx.x)
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: 参与者或其法定代理人撤回知情同意
    Order: 1
    Aval: xx (xx.x)|xx (xx.x)|xx (xx.x)
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: 死亡
    Order: 1
    Aval: xx (xx.x)|xx (xx.x)|xx (xx.x)
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: 失访
    Order: 1
    Aval: xx (xx.x)|xx (xx.x)|xx (xx.x)
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: 本研究终止
    Order: 1
    Aval: xx (xx.x)|xx (xx.x)|xx (xx.x)
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: 完成规定时限的研究
    Order: 1
    Aval: xx (xx.x)|xx (xx.x)|xx (xx.x)
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: 其他
    Order: 1
    Aval: xx (xx.x)|xx (xx.x)|xx (xx.x)
    exclude: 0
    BlankCol: ''
  ds_2:
  - Class: ''
    Label: 年龄（岁）
    Order: 0
    Aval: '||'
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: 例数
    Order: 1
    Aval: xx|xx|xx
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: 均值（标准差）
    Order: 1
    Aval: xx.x (xx.xx)|xx.x (xx.xx)|xx.x (xx.xx)
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: 中位数
    Order: 1
    Aval: xx.x|xx.x|xx.x
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: 最小值 - 最大值
    Order: 1
    Aval: xx – xx|xx – xx|xx – xx
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: ''
    Order: 0
    Aval: '||'
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: 年龄分组，n (%)
    Order: 0
    Aval: '||'
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: <65岁
    Order: 1
    Aval: xx (xx.x)|xx (xx.x)|xx (xx.x)
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: ≥65 岁
    Order: 1
    Aval: xx (xx.x)|xx (xx.x)|xx (xx.x)
    exclude: 0
    BlankCol: ''
  ds_3:
  - Class: ''
    Label: 系统器官分类 (SOC) /首选术语 (PT))
    Order: 0
    Aval: 所有级别|≥3级|所有级别|≥3级
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: 所有TEAE
    Order: 0
    Aval: xx (xx.x)|xx (xx.x)|xx (xx.x)|xx (xx.x)
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: ''
    Order: 0
    Aval: '|||'
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: <SOC 1>
    Order: 0
    Aval: xx (xx.x)|xx (xx.x)|xx (xx.x)|xx (xx.x)
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: <PT1>
    Order: 2
    Aval: xx (xx.x)|xx (xx.x)|xx (xx.x)|xx (xx.x)
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: <PT2>
    Order: 2
    Aval: xx (xx.x)|xx (xx.x)|xx (xx.x)|xx (xx.x)
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: <PT3>
    Order: 2
    Aval: xx (xx.x)|xx (xx.x)|xx (xx.x)|xx (xx.x)
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: ''
    Order: 0
    Aval: '|||'
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: <SOC 2>
    Order: 0
    Aval: xx (xx.x)|xx (xx.x)|xx (xx.x)|xx (xx.x)
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: <PT1>
    Order: 2
    Aval: xx (xx.x)|xx (xx.x)|xx (xx.x)|xx (xx.x)
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: <PT2>
    Order: 2
    Aval: xx (xx.x)|xx (xx.x)|xx (xx.x)|xx (xx.x)
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: <PT3>
    Order: 2
    Aval: xx (xx.x)|xx (xx.x)|xx (xx.x)|xx (xx.x)
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: ''
    Order: 0
    Aval: '|||'
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: …
    Order: 0
    Aval: …|…|…|…
    exclude: 0
    BlankCol: ''
  ds_4:
  - Class: ''
    Label: 基线
    Order: 0
    Aval: '|'
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: 例数
    Order: 1
    Aval: xx (xx)|xx (xx)
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: 均值（标准差）
    Order: 1
    Aval: xx.x (xx.xx)|xx.x (xx.xx)
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: 中位数
    Order: 1
    Aval: xx.x|xx.x
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: 最小值,最大值
    Order: 1
    Aval: xx,xx|xx,xx
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: ''
    Order: 0
    Aval: '|'
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: <重复其他分析访视>
    Order: 0
    Aval: '|'
    exclude: 0
    BlankCol: ''
  ds_5:
  - Class: ''
    Label: 基线
    Order: 0
    Aval: ADA阴性|xx
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: ''
    Order: 0
    Aval: ADA阳性|xx.xx (xx.xxx)
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: ''
    Order: 0
    Aval: Nab阴性|xx.xx
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: ''
    Order: 0
    Aval: Nab阳性|xx.xx
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: ''
    Order: 0
    Aval: 缺失|xx.x – xx.x
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: ''
    Order: 0
    Aval: '|'
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: CxDy
    Order: 0
    Aval: ADA阴性|xx
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: ''
    Order: 0
    Aval: ADA阳性|xx.xx (xx.xxx)
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: ''
    Order: 0
    Aval: Nab阴性|xx.xx
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: ''
    Order: 0
    Aval: Nab阳性|xx.xx
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: ''
    Order: 0
    Aval: 缺失|xx.x – xx.x
    exclude: 0
    BlankCol: ''
  list:
  - Class: ''
    Label: ''
    Order: 0
    Aval: '||||||||'
    exclude: 0
    BlankCol: ''
  - Class: ''
    Label: ''
    Order: 0
    Aval: '||||||||'
    exclude: 0
    BlankCol: ''
