version: 1
config:
- SeqNum: 1
  Section no: '14.2'
  Section title: 疗效分析
  cat: 图
  table no: 14.2.3.1
  title: IRC基于2014 Lugano淋巴瘤疗效评价标准评估的无进展生存期（PFS）Kaplan-Meier曲线图
  pop: ITT
  MacVar: KMplot
  Datasets: survival
  Trtlab: 试验组(N=xx)|对照组(N=xx)
  Subgrp: ''
  Adcols: ''
  Varlab: ''
  Labparm: ''
  footnote1: 无进展生存期(PFS)定义为从随机化日期至首次IRC基于Lugano 2014 评效标准评价为疾病进展或任何原因导致死亡（以先发生者为准）日期之间的时间。PFS时间（月）计算为（首次PD或死亡/删失日期-随机化日期
    + 1）/30.4375。
  footnote2: ''
  footnote3: ''
  footnote4: ''
  footnote5: ''
  footnote6: ''
  footnote7: ''
  PgmNotes: ''
  ByseqL: ''
  RefTFL: ''
  Dutoffdate: ''
  Source_Data: 列表 16.2.6.9.1
datasets:
  survival:
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
  - Class: ''
    Label: ''
    Order: null
    Aval: ''
    exclude: null
    BlankCol: ''
    Drug: ''
    Visit: ''
    Base: ''
